# Generated by Django 4.0.4 on 2022-05-21 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pipeline', models.CharField(max_length=200, unique=True)),
                ('empresa', models.CharField(max_length=100)),
                ('redesocal', models.CharField(max_length=100)),
                ('dt_criacao', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
