# Generated by Django 4.0.4 on 2022-05-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='empresa',
            field=models.CharField(choices=[('EQUIPE', 'EQUIPE'), ('FCB', 'FCB'), ('GALERIA', 'GALERIA'), ('DPZT', 'DPZT')], max_length=50, null=True),
        ),
    ]
