# Generated by Django 4.0.4 on 2022-04-23 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bio',
            new_name='grupo',
        ),
    ]
