# Generated by Django 4.0.4 on 2022-04-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_rename_bio_user_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grupo',
            field=models.CharField(max_length=1),
        ),
    ]
