# Generated by Django 4.0.4 on 2022-04-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_user_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grupo',
            field=models.CharField(choices=[('0', 'FCB'), ('1', 'GALERIA'), ('2', 'DPZT')], max_length=50),
        ),
    ]
