# Generated by Django 4.0.4 on 2022-04-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_user_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grupo',
            field=models.CharField(choices=[('FCB', 'FCB'), ('GALERIA', 'GALERIA'), ('DPZT', 'DPZT')], max_length=50),
        ),
    ]
