# Generated by Django 4.0.4 on 2022-05-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_user_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grupo',
            field=models.CharField(choices=[('FCB', 'FCB'), ('GALERIA', 'GALERIA'), ('DPZT', 'DPZT')], max_length=50, null=True),
        ),
    ]
